"""removed gender column

Revision ID: 948dd5d647a3
Revises: 76f92ccd0dad
Create Date: 2026-07-23 11:05:09.578897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948dd5d647a3'
down_revision: Union[str, Sequence[str], None] = '76f92ccd0dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'gender')
    op.add_column('order_items', sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'unit_price')
    op.add_column('customers', sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
